// <auto-generated />
namespace ProvaCandidato.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_bd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_bd));
        
        string IMigrationMetadata.Id
        {
            get { return "202201231429512_create_bd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
